repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Sanity checks
      - id: check-merge-conflict
      # Check syntax of files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
  # Static analysis
  - repo: https://github.com/PyCQA/prospector
    rev: 1.7.7
    hooks:
      - id: prospector
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
  # Format Python code (incl. Jupyter notebooks)
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black-jupyter
        language_version: python3.10
  # Export requirements.txt
  - repo: https://github.com/pdm-project/pdm
    rev: 2.1.5
    hooks:
      - id: pdm-export
        # command arguments, e.g.:
        args: ["-o", "requirements.txt", "--without-hashes"]
        files: ^pdm.lock$
  # Vulnerability scan of dependencies
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
