# See GitHub Actions Release workflow for tests and deployment
# file:///Users/ao/Documents/AO/monkeytale/.github/workflows/release.yml

repos:
  # COMMIT MESSAGE CHECKS
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]

  # INTEGRITY & SYNTAX CHECKS
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # File integrity checks
      - id: check-merge-conflict
      - id: mixed-line-ending
      # Syntax checks
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml

  # LINTING & STATIC CODE ANALYSIS
  # Dead code
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.6
    hooks:
      - id: vulture
  # Best practices
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-no-eval
      - id: python-use-type-annotations
  # Security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
  # Secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  # FORMAT PYTHON CODE (INCL. JUPYTER NOTEBOOKS)
  # Sort imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.5
    hooks:
      - id: reorder-python-imports
  # Format code
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black-jupyter
        language_version: python3.10

  # EXPORT PYTHON REQUIREMENTS.TXT FROM PDM.LOCK
  - repo: https://github.com/pdm-project/pdm
    rev: 2.1.5
    hooks:
      - id: pdm-export
        args: [-o, requirements.txt, --without-hashes]
        files: ^pdm.lock$

  # VULNERABILITY SCAN OF DEPENDENCIES
  # Must follow PDM export so it can pick up the requirements.txt
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        files: requirements
