repos:
  # Sanity & syntax checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml

  # Static code analysis
  - repo: https://github.com/PyCQA/prospector
    rev: 1.7.7
    hooks:
      - id: prospector
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  # Format Python code (incl. Jupyter notebooks)
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black-jupyter
        language_version: python3.10

  # Export Python requirements.txt from pdm.lock
  - repo: https://github.com/pdm-project/pdm
    rev: 2.1.5
    hooks:
      - id: pdm-export
        args: [-o, requirements.txt, --without-hashes]
        files: ^pdm.lock$

  # Vulnerability scan of dependencies
  # Must follow PDM export so it can pick up the requirements.txt
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
