# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482

name: Monkeytale Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check-out
        uses: actions/checkout@v2
      - name: Install PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10" # Same as actions/setup-python
          architecture: x64 # Same as actions/setup-python
          # version: 1.4.0 # The version of PDM to install. Leave empty to use latest from PyPI
          prerelease: false # Allow prereleases
          enable-pep582: true # Enable PEP 582 globally
      - name: Install application & dependencies
        run: |
          pdm --version
          pdm install -dG test
      - name: Unit test application
        run: |
          pdm run pytest --version
          pdm run pytest -v ./tests
      - name: Source code security analysis
        run: |
          pdm run bandit --version
          pdm run bandit --recursive --skip B101 -x ./tests -x ./__pypackages__ .
      - name: Export PDM config to Poetry for Snyk to read
        run: pdm export -f poetry
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  Deploy:
    needs: [Test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release)')

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      # Set environment variables for Python Semantic Release to pick-up
      REPOSITORY_USERNAME: __token__
      REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    steps:
      - name: Check-out with history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Pull history for semantic versioning from commit messages
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Python Semantic Release
        run: |
          pip install python-semantic-release
          git config user.name semantic-release
          git config user.email semantic-release@dwlib.com
      - name: Publish application to pypi.org
        run: semantic-release publish -D repository=pypi
      - name: Record version
        run: |
          mkdir -p artifacts/Deploy
          semantic-release --current print-version | awk '{print $1}' > artifacts/Deploy/semver
      - uses: actions/upload-artifact@v3
        with:
          name: Deploy
          path: artifacts/Deploy/*
          retention-days: 7 # Do not waste space indefinitely

  # Confirm deployment to PyPI was successful
  TestDeploy:
    needs: [Deploy]

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Give PyPI time to expose new version
        run: sleep 15
      - name: Install PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10" # Same as actions/setup-python
          architecture: x64 # Same as actions/setup-python
          # version: 1.4.0 # Which PDM version, empty uses latest from PyPI
          prerelease: false # Do not allow prerelease
          enable-pep582: true # Enable PEP 582 globally
      - name: Pull artifacts from Deploy
        uses: actions/download-artifact@v3
        with:
          name: Deploy
          path: artifacts/Deploy
      - name: Compare expected and found versions
        run: |
          pdm init -n
          pdm add monkeytale
          mkdir -p artifacts/TestDeploy
          pdm run @ --version | awk '{print $3}' > artifacts/TestDeploy/semver
          echo "Expected v$(cat artifacts/Deploy/semver) and found v$(cat artifacts/TestDeploy/semver)"
          diff artifacts/TestDeploy/semver artifacts/Deploy/semver
